### ISSUE TITLE
Binary isn't a function while using binary flag with socket.io-emitter

### ISSUE THREAD

**Issue by dverbovyi** [socketio/socket.io-emitter#86]
Hello
I would like to use this binary flag https://socket.io/docs/server-api/#Flag-%E2%80%98binary%E2%80%99-1 but haven't found any example with io-emitter
Applying it to socket.io-emitter throws `binary isn't a function` 

Thanks in advance

**Comment by darrachequesne** [comment]
The `binary` flag is specific to the Socket.IO server, as the `socket.io-emitter` library directly encode the packet with [msgpack](https://msgpack.org/). That's why it is not applicable here.

Note: this flag was removed in Socket.IO v3 (https://github.com/socketio/socket.io/commit/669592d120409a5cf00f128070dee6d22259ba4f)
